services:
  spl-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spl-docs
    restart: unless-stopped
    ports:
      - "4003:3000"
    env_file:
      - .env
    environment:
      - API_SPEC_URL=${API_SPEC_URL:-https://na-maps.vng-solutions.com/spl/openapi.json}
